import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.58.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface SunoTask {
  clip_id: string;
  state: string;
  title: string;
  tags: string;
  lyrics: string;
  image_url: string;
  audio_url: string;
  video_url: string | null;
  created_at: string;
  duration: string | null;
}

interface SunoResponse {
  code: number;
  data: SunoTask[];
  message: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('Starting pending songs check...');

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const sunoApiKey = Deno.env.get('SUNO_API_KEY');

    if (!sunoApiKey) {
      throw new Error('SUNO_API_KEY not found in environment variables');
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get all songs with generating status
    const { data: pendingSongs, error: fetchError } = await supabase
      .from('songs')
      .select('*')
      .eq('status', 'generating')
      .order('created_at', { ascending: true });

    if (fetchError) {
      console.error('Error fetching pending songs:', fetchError);
      throw fetchError;
    }

    console.log(`Found ${pendingSongs?.length || 0} pending songs to check`);

    if (!pendingSongs || pendingSongs.length === 0) {
      return new Response(JSON.stringify({ 
        success: true, 
        message: 'No pending songs found',
        checked: 0,
        updated: 0 
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    let updatedCount = 0;
    let errorCount = 0;

    // Check each pending song
    for (const song of pendingSongs) {
      try {
        console.log(`Checking song: ${song.id} (${song.title || 'Untitled'})`);

        // Skip songs that don't have a prompt (likely corrupted)
        if (!song.prompt || song.prompt.trim() === '') {
          console.log(`Skipping song ${song.id} - no prompt found`);
          continue;
        }

        // Extract potential Suno task ID from song description or other fields
        // For songs generated by the build-prompt system, we need to query Suno API
        // Since we don't store the task ID directly, we'll need to search by prompt or other criteria
        
        // Try to find the song by checking recent Suno API results
        // This is a bit of a workaround since we don't have direct task IDs for old songs
        console.log(`Attempting to find Suno task for song ${song.id} with prompt: ${song.prompt.substring(0, 50)}...`);
        
        // For now, let's mark old generating songs as failed if they're older than 1 hour
        const songAge = new Date().getTime() - new Date(song.created_at).getTime();
        const oneHourInMs = 60 * 60 * 1000;
        
        if (songAge > oneHourInMs) {
          console.log(`Song ${song.id} is older than 1 hour, marking as failed`);
          
          const { error: updateError } = await supabase
            .from('songs')
            .update({ 
              status: 'failed',
              updated_at: new Date().toISOString()
            })
            .eq('id', song.id);

          if (updateError) {
            console.error(`Error updating song ${song.id}:`, updateError);
            errorCount++;
          } else {
            console.log(`Successfully marked song ${song.id} as failed`);
            updatedCount++;
          }
        } else {
          // For newer songs, we could try to check with Suno API
          // But without the task ID, this is challenging
          console.log(`Song ${song.id} is recent (${Math.round(songAge / 1000 / 60)} minutes old), keeping as generating`);
        }

        // Add a small delay to avoid rate limiting
        await new Promise(resolve => setTimeout(resolve, 100));

      } catch (error) {
        console.error(`Error processing song ${song.id}:`, error);
        errorCount++;
      }
    }

    console.log(`Completed check: ${updatedCount} songs updated, ${errorCount} errors`);

    return new Response(JSON.stringify({
      success: true,
      message: `Checked ${pendingSongs.length} pending songs`,
      checked: pendingSongs.length,
      updated: updatedCount,
      errors: errorCount,
      details: `Marked ${updatedCount} old songs as failed, ${errorCount} errors occurred`
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in check-pending-songs function:', error);
    return new Response(JSON.stringify({ 
      success: false, 
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});