import { useState, useEffect, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import {
  Play, Pause, SkipForward, ThumbsUp, ThumbsDown, Radio, Sparkles, Zap,
  LogIn, LogOut, Shield, User as UserIcon, Volume2, Library, ListMusic,
  Info, ListPlus, Save, FlaskConical, Snowflake, Ghost, Clover, Flag,
} from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { useAdmin } from '@/hooks/useAdmin';
import { useRadio, Song, Taste } from '@/hooks/useRadio';
import { useAudioPlayer } from '@/contexts/AudioContext';
import { AddToPlaylistDialog } from '@/components/AddToPlaylistDialog';
import SongBrowser from '@/components/SongBrowser';
import PlaylistsView from '@/components/PlaylistsView';
import AuthPage from './AuthPage';

const MOODS = ['upbeat', 'chill', 'aggressive', 'emotional', 'epic', 'playful'];
const FALLBACK_GENRES = ['classical', 'edm', 'pop', 'rock', 'jazz', 'hip-hop', 'country'];

const HOLIDAYS = [
  { name: 'christmas', icon: Snowflake, emoji: null },
  { name: 'halloween', icon: Ghost, emoji: null },
  { name: 'hanukkah', icon: null, emoji: '🕎' },
  { name: 'thanksgiving', icon: null, emoji: '🍗' },
  { name: "st. patty's day", icon: Clover, emoji: null },
  { name: '4th of july', icon: Flag, emoji: null },
];

// Deterministic artwork gradient per genre, for tracks without cover art
const GENRE_HUES: Record<string, [number, number]> = {
  classical: [36, 20], edm: [190, 280], pop: [320, 40], rock: [0, 25],
  jazz: [260, 30], 'hip-hop': [280, 200], country: [30, 90],
};

function genreArt(genre: string): string {
  const [h1, h2] = GENRE_HUES[genre?.toLowerCase()] ?? [220, 300];
  return `conic-gradient(from 220deg at 40% 40%, hsl(${h1} 70% 45%), hsl(${h2} 65% 30%), hsl(${h1} 80% 15%), hsl(${h2} 70% 40%), hsl(${h1} 70% 45%))`;
}

function formatTime(seconds: number): string {
  if (!isFinite(seconds) || seconds <= 0) return '0:00';
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

/** The "why this track" line — every song arrives with a story. */
function trackStory(song: Song, taste: Taste, stationId: string | null): string {
  if (stationId && song.station_id === stationId) {
    return 'Composed for this station — your taste aimed the studio here.';
  }
  const genreAffinity = taste[`genre:${song.genre?.toLowerCase()}`] ?? 0;
  const moodAffinity = song.mood ? taste[`mood:${song.mood.toLowerCase()}`] ?? 0 : 0;
  if (genreAffinity >= 2 && moodAffinity >= 2) {
    return `Picked because you've been loving ${song.mood} ${song.genre} lately.`;
  }
  if (genreAffinity >= 2) {
    return `Your station leans ${song.genre} — this one scored high for you.`;
  }
  if (song.holiday) {
    return `A ${song.holiday} special, straight from the AI songbook.`;
  }
  if (song.description) return song.description;
  return `Fresh pick from the ${song.genre} shelf, generated by AI.`;
}

/** Summarize the taste vector into human words. */
function tasteSummary(taste: Taste): { loving: string[]; avoiding: string[] } {
  const entries = Object.entries(taste).map(([k, v]) => ({ label: k.split(':')[1], v }));
  return {
    loving: entries.filter((e) => e.v >= 2).sort((a, b) => b.v - a.v).slice(0, 3).map((e) => e.label),
    avoiding: entries.filter((e) => e.v <= -2).sort((a, b) => a.v - b.v).slice(0, 2).map((e) => e.label),
  };
}

export default function RadioPage() {
  const { user, signOut } = useAuth();
  const { isAdmin } = useAdmin();
  const {
    status, settings, current, upNext, station, taste, brewing, lastFeedback,
    tuneIn, skip, like, dislike, steer, saveStation,
  } = useRadio();
  const { isPlaying, progress, duration, volume, setVolume, seekTo, playSong } = useAudioPlayer();

  const [genres, setGenres] = useState<string[]>(FALLBACK_GENRES);
  const [showAuth, setShowAuth] = useState(false);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [showPlaylistDialog, setShowPlaylistDialog] = useState(false);
  const [stationName, setStationName] = useState('');
  const [saveOpen, setSaveOpen] = useState(false);

  // Force dark mode — this is a night-drive product
  useEffect(() => {
    document.documentElement.classList.add('dark');
  }, []);

  // The dial only offers frequencies that actually have music
  useEffect(() => {
    import('@/integrations/supabase/client').then(({ supabase }) =>
      supabase.rpc('library_genres').then(({ data }) => {
        if (data && data.length > 0) setGenres(data.map((g) => g.genre));
      })
    );
  }, []);

  // Close the auth overlay the moment sign-in succeeds
  useEffect(() => {
    if (user) setShowAuth(false);
  }, [user]);

  const onAir = status === 'on-air' && current;
  const story = useMemo(
    () => (current ? trackStory(current, taste, station?.id ?? null) : ''),
    [current, taste, station]
  );
  const tasteWords = useMemo(() => tasteSummary(taste), [taste]);

  const toggleGenre = (g: string) => {
    const next = settings.genres.includes(g)
      ? settings.genres.filter((x) => x !== g)
      : [...settings.genres, g];
    steer({ genres: next });
  };

  const requireAuth = (action: () => void) => {
    if (!user) { setShowAuth(true); return; }
    action();
  };

  const handleSave = async () => {
    const name = stationName.trim() ||
      (settings.genres.length > 0 ? `${settings.genres.join(' + ')} FM` : 'My Station');
    if (await saveStation(name)) setSaveOpen(false);
  };

  return (
    <div className="min-h-screen radio-gradient">
      {/* ---------- top bar ---------- */}
      <header className="sticky top-0 z-20 backdrop-blur-md bg-background/70 border-b border-border/40">
        <div className="max-w-5xl mx-auto flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-full bg-primary/15">
              <Radio className="h-5 w-5 text-primary" />
            </div>
            <span className="font-bold text-lg tracking-tight">
              Spark<span className="text-primary"> Radio</span>
            </span>
            {station && (
              <Badge variant="secondary" className="ml-2 hidden sm:inline-flex">
                {station.name}
              </Badge>
            )}
          </div>
          <div className="flex items-center gap-2">
            {isAdmin && (
              <Button variant="ghost" size="sm" asChild>
                <Link to="/admin"><Shield className="h-4 w-4 mr-1" />Admin</Link>
              </Button>
            )}
            {user ? (
              <>
                <span className="hidden md:flex items-center gap-1 text-sm text-muted-foreground">
                  <UserIcon className="h-4 w-4" />{user.email}
                </span>
                <Button variant="ghost" size="sm" onClick={() => signOut()}>
                  <LogOut className="h-4 w-4 mr-1" />Sign out
                </Button>
              </>
            ) : (
              <Button variant="outline" size="sm" onClick={() => setShowAuth(true)}>
                <LogIn className="h-4 w-4 mr-1" />Sign in
              </Button>
            )}
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-8 space-y-8">
        {/* ---------- hero / now playing ---------- */}
        {!onAir ? (
          <section className="text-center space-y-8 py-8 animate-fade-in-up">
            <div className="space-y-3">
              <h1 className="text-4xl md:text-5xl font-bold tracking-tight">
                Your station.{' '}
                <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                  Composed while you listen.
                </span>
              </h1>
              <p className="text-lg text-muted-foreground max-w-xl mx-auto">
                Pick a vibe and press play — music starts instantly from a library of{' '}
                AI-made tracks, and new ones are composed for you in the background.
              </p>
            </div>

            <Card className="max-w-2xl mx-auto bg-card/60 backdrop-blur-sm border-border/50 text-left">
              <CardContent className="p-6 space-y-6">
                <div className="space-y-3">
                  <p className="text-sm font-medium text-muted-foreground uppercase tracking-wider">Genres <span className="normal-case font-normal">(none = surprise me)</span></p>
                  <div className="flex flex-wrap gap-2">
                    {genres.map((g) => (
                      <button key={g} onClick={() => toggleGenre(g)}
                        className={`genre-chip ${settings.genres.includes(g) ? 'selected' : ''}`}>
                        {g}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="space-y-3">
                  <p className="text-sm font-medium text-muted-foreground uppercase tracking-wider">Mood</p>
                  <div className="flex flex-wrap gap-2">
                    {MOODS.map((m) => (
                      <button key={m}
                        onClick={() => steer({ mood: settings.mood === m ? null : m })}
                        className={`genre-chip ${settings.mood === m ? 'selected' : ''}`}>
                        {m}
                      </button>
                    ))}
                  </div>
                </div>

                <button onClick={() => setShowAdvanced(!showAdvanced)}
                  className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                  {showAdvanced ? '▾' : '▸'} More knobs
                </button>
                {showAdvanced && (
                  <div className="space-y-4 animate-fade-in-up">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2 text-sm">
                        <Volume2 className="h-4 w-4 text-muted-foreground" /> Instrumental only
                      </div>
                      <Switch checked={settings.instrumental}
                        onCheckedChange={(v) => steer({ instrumental: v })} />
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2 text-sm">
                        <Zap className="h-4 w-4 text-muted-foreground" /> Wildcard twists
                      </div>
                      <Switch checked={settings.wildcard}
                        onCheckedChange={(v) => steer({ wildcard: v })} />
                    </div>
                    <div className="grid grid-cols-3 gap-2">
                      {HOLIDAYS.map((h) => {
                        const Icon = h.icon;
                        const active = settings.holiday === h.name;
                        return (
                          <button key={h.name}
                            onClick={() => steer({ holiday: active ? null : h.name })}
                            className={`flex flex-col items-center p-2 rounded-lg border transition-all text-xs ${
                              active ? 'border-primary bg-primary/10 text-primary' : 'border-border hover:border-primary/50'
                            }`}>
                            {Icon ? <Icon className="h-4 w-4 mb-1" /> : <span className="text-lg mb-0.5">{h.emoji}</span>}
                            {h.name}
                          </button>
                        );
                      })}
                    </div>
                  </div>
                )}

                <Button onClick={() => tuneIn()} disabled={status === 'tuning'}
                  className="w-full h-14 text-lg font-semibold neon-glow" size="lg">
                  <Play className="h-6 w-6 mr-2" />
                  {status === 'tuning' ? 'Tuning…' : 'Tune in'}
                </Button>
                <p className="text-xs text-center text-muted-foreground">
                  No account needed to listen. Sign in when you want the station to learn your taste.
                </p>
              </CardContent>
            </Card>
          </section>
        ) : (
          <section className="space-y-6 animate-fade-in-up">
            {/* Now playing card */}
            <Card className="bg-card/60 backdrop-blur-sm border-border/50 overflow-hidden">
              <CardContent className="p-6 md:p-8">
                <div className="flex flex-col md:flex-row gap-8 items-center">
                  {/* artwork */}
                  <div className="relative shrink-0">
                    <div
                      className={`w-48 h-48 md:w-56 md:h-56 rounded-full border-4 border-border/60 shadow-2xl overflow-hidden ${isPlaying ? 'vinyl-spin' : ''}`}
                      style={current.image_url
                        ? { backgroundImage: `url(${current.image_url})`, backgroundSize: 'cover', backgroundPosition: 'center' }
                        : { background: genreArt(current.genre) }}
                    >
                      <div className="absolute inset-0 m-auto w-10 h-10 rounded-full bg-background border-2 border-border/80" />
                    </div>
                    {brewing.length > 0 && (
                      <div className="absolute -bottom-1 -right-1 p-2 rounded-full bg-accent/90 text-accent-foreground animate-glow-pulse" title={`${brewing.length} track(s) being composed for this station`}>
                        <FlaskConical className="h-4 w-4" />
                      </div>
                    )}
                  </div>

                  {/* track info + controls */}
                  <div className="flex-1 w-full space-y-4 text-center md:text-left">
                    <div className="space-y-2">
                      <div className="flex items-center justify-center md:justify-start gap-2 flex-wrap">
                        <Badge variant="outline" className="uppercase tracking-wide text-[10px]">{current.genre}</Badge>
                        {current.mood && <Badge variant="secondary" className="text-[10px]">{current.mood}</Badge>}
                        {current.holiday && <Badge className="text-[10px] bg-accent text-accent-foreground">{current.holiday}</Badge>}
                      </div>
                      <h2 className="text-2xl md:text-3xl font-bold">{current.title ?? 'Untitled'}</h2>
                      <p className="text-sm text-muted-foreground italic flex items-center justify-center md:justify-start gap-1.5">
                        <Sparkles className="h-3.5 w-3.5 text-primary shrink-0" />{story}
                      </p>
                    </div>

                    {/* progress */}
                    <div className="space-y-1">
                      <div className="progress-bar cursor-pointer h-2" onClick={(e) => {
                        const rect = e.currentTarget.getBoundingClientRect();
                        seekTo(((e.clientX - rect.left) / rect.width) * 100);
                      }}>
                        <div className="progress-fill" style={{ width: `${progress}%` }} />
                      </div>
                      <div className="flex justify-between text-xs text-muted-foreground">
                        <span>{formatTime((progress / 100) * duration)}</span>
                        <span>{formatTime(duration)}</span>
                      </div>
                    </div>

                    {/* controls */}
                    <div className="flex items-center justify-center md:justify-start gap-3 flex-wrap">
                      <Button variant="ghost" size="icon"
                        className={lastFeedback === 'dislike' ? 'text-destructive' : 'text-muted-foreground hover:text-destructive'}
                        onClick={() => requireAuth(dislike)} title="Not my thing — teach the station">
                        <ThumbsDown className="h-5 w-5" />
                      </Button>

                      <Button size="icon" className="h-14 w-14 rounded-full neon-glow"
                        onClick={() => playSong({
                          id: current.id, title: current.title ?? 'Untitled', url: current.url ?? undefined,
                          genre: current.genre, mood: current.mood ?? undefined, image_url: current.image_url ?? undefined,
                        }, 'player')}>
                        {isPlaying ? <Pause className="h-7 w-7" /> : <Play className="h-7 w-7 ml-0.5" />}
                      </Button>

                      <Button variant="ghost" size="icon" onClick={skip} title="Skip">
                        <SkipForward className="h-5 w-5" />
                      </Button>

                      <Button variant="ghost" size="icon"
                        className={lastFeedback === 'like' ? 'text-primary' : 'text-muted-foreground hover:text-primary'}
                        onClick={() => requireAuth(like)} title="More like this — teach the station">
                        <ThumbsUp className="h-5 w-5" />
                      </Button>

                      <Button variant="ghost" size="icon" className="text-muted-foreground"
                        onClick={() => requireAuth(() => setShowPlaylistDialog(true))} title="Add to playlist">
                        <ListPlus className="h-5 w-5" />
                      </Button>

                      <Popover>
                        <PopoverTrigger asChild>
                          <Button variant="ghost" size="icon" className="text-muted-foreground" title="The recipe">
                            <Info className="h-5 w-5" />
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-80 text-sm">
                          <p className="font-medium mb-1">The recipe</p>
                          <p className="text-muted-foreground">{current.prompt}</p>
                        </PopoverContent>
                      </Popover>

                      <div className="flex items-center gap-2 ml-auto min-w-28">
                        <Volume2 className="h-4 w-4 text-muted-foreground shrink-0" />
                        <Slider value={[volume]} onValueChange={(v) => setVolume(v[0])} max={100} step={1} className="w-20" />
                      </div>
                    </div>

                    {upNext && (
                      <p className="text-xs text-muted-foreground">
                        Up next: <span className="text-foreground/80">{upNext.title ?? upNext.genre}</span>
                      </p>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* steering strip: the dial stays under your hand */}
            <Card className="bg-card/40 backdrop-blur-sm border-border/40">
              <CardContent className="p-4 space-y-3">
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Zap className="h-4 w-4 text-primary" />
                  Steer the station — changes take effect on the next track
                </div>
                <div className="flex flex-wrap gap-2">
                  {genres.map((g) => (
                    <button key={g} onClick={() => toggleGenre(g)}
                      className={`genre-chip text-sm ${settings.genres.includes(g) ? 'selected' : ''}`}>
                      {g}
                    </button>
                  ))}
                  <span className="w-px bg-border mx-1 self-stretch" />
                  {MOODS.map((m) => (
                    <button key={m}
                      onClick={() => steer({ mood: settings.mood === m ? null : m })}
                      className={`genre-chip text-sm ${settings.mood === m ? 'selected' : ''}`}>
                      {m}
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* station bar: save point / taste readout */}
            <div className="flex flex-col sm:flex-row items-center justify-between gap-3 px-1">
              {station ? (
                <div className="flex items-center gap-2 text-sm text-muted-foreground flex-wrap">
                  <Radio className="h-4 w-4 text-primary" />
                  <span className="font-medium text-foreground">{station.name}</span>
                  {tasteWords.loving.length > 0 && (
                    <span>· loving <span className="text-primary">{tasteWords.loving.join(', ')}</span></span>
                  )}
                  {tasteWords.avoiding.length > 0 && (
                    <span>· avoiding <span className="text-destructive">{tasteWords.avoiding.join(', ')}</span></span>
                  )}
                  {tasteWords.loving.length === 0 && tasteWords.avoiding.length === 0 && (
                    <span>· still learning your taste — like and skip freely</span>
                  )}
                </div>
              ) : (
                <Popover open={saveOpen} onOpenChange={setSaveOpen}>
                  <PopoverTrigger asChild>
                    <Button variant="outline" size="sm"
                      onClick={(e) => { if (!user) { e.preventDefault(); setShowAuth(true); } }}>
                      <Save className="h-4 w-4 mr-2" />Save this station
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-72 space-y-3">
                    <p className="text-sm font-medium">Name your station</p>
                    <Input value={stationName} onChange={(e) => setStationName(e.target.value)}
                      placeholder={settings.genres.length ? `${settings.genres.join(' + ')} FM` : 'My Station'}
                      onKeyDown={(e) => e.key === 'Enter' && handleSave()} />
                    <Button size="sm" className="w-full" onClick={handleSave}>Put it on the air</Button>
                    <p className="text-xs text-muted-foreground">
                      A saved station remembers your taste and commissions fresh tracks aimed at it.
                    </p>
                  </PopoverContent>
                </Popover>
              )}

              {/* in the studio */}
              {brewing.length > 0 && (
                <div className="flex items-center gap-3 text-sm text-muted-foreground">
                  <span className="flex items-end gap-0.5 h-4">
                    <span className="eq-bar" style={{ animationDelay: '0ms' }} />
                    <span className="eq-bar" style={{ animationDelay: '150ms' }} />
                    <span className="eq-bar" style={{ animationDelay: '300ms' }} />
                  </span>
                  In the studio: {brewing.map((b) => b.genre).join(', ')} —{' '}
                  {brewing.length === 1 ? 'a new track is' : `${brewing.length} new tracks are`} being composed for you
                </div>
              )}
            </div>
          </section>
        )}

        {/* ---------- library ---------- */}
        <Tabs defaultValue="browse" className="w-full">
          <TabsList className="grid w-full max-w-md mx-auto grid-cols-2">
            <TabsTrigger value="browse" className="flex items-center gap-2">
              <Library className="h-4 w-4" />Browse
            </TabsTrigger>
            <TabsTrigger value="playlists" className="flex items-center gap-2">
              <ListMusic className="h-4 w-4" />Playlists
            </TabsTrigger>
          </TabsList>
          <TabsContent value="browse">
            <Card className="bg-card/40 backdrop-blur-sm border-border/40">
              <CardContent className="p-6"><SongBrowser /></CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="playlists">
            <Card className="bg-card/40 backdrop-blur-sm border-border/40">
              <CardContent className="p-6"><PlaylistsView /></CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </main>

      {/* add-to-playlist */}
      <AddToPlaylistDialog
        song={current ? { id: current.id, title: current.title ?? 'Untitled' } : null}
        open={showPlaylistDialog}
        onOpenChange={setShowPlaylistDialog}
      />

      {/* auth overlay — listening never requires it; teaching the station does */}
      {showAuth && (
        <div className="fixed inset-0 z-50 overflow-auto bg-background">
          <AuthPage onBack={() => setShowAuth(false)} />
        </div>
      )}
    </div>
  );
}
