-- Add 50 new prompt templates from the expanded_prompt_templates.csv
INSERT INTO public.prompt_templates (template) VALUES 
('A {mood} {genre} track featuring {instrument} with {twist}.'),
('Create {mood} {genre} sounds with {instrument} and {tempo} pacing.'),
('A {tempo}, {mood} {genre} piece performed {setting}.'),
('A {mood} {genre} composition inspired by {era}, with {instrument}.'),
('An {energy} {genre} jam featuring {instrument} and {twist}.'),
('Craft a {mood} {genre} with {tempo} rhythms and {instrument} textures.'),
('A {genre} anthem that feels {mood}, played {setting} with {twist}.'),
('Compose {genre} music that is {mood} and {energy}, led by {instrument}.'),
('A {mood}, {tempo} {genre} inspired by {era}, with {instrument} layers.'),
('Imagine {setting}: a {mood} {genre} song with {instrument} and {twist}.'),
('A {mood} {genre} ballad with {instrument} and {tempo} groove.'),
('A {genre} track blending {era} influence with {mood} vibes and {twist}.'),
('Write a {mood} {genre} tune that is {energy}, featuring {instrument}.'),
('A {tempo} {genre} song evoking {mood}, played {setting}.'),
('A {genre} mix of {era} style and {twist}, with {instrument}.'),
('An {energy} {mood} {genre} that uses {instrument} in {setting}.'),
('A {genre} song with {instrument}, {tempo} beat, and {twist}.'),
('A {mood} {genre} in the style of {era}, with {energy} intensity.'),
('Compose {genre} with {instrument}, {twist}, and {setting}.'),
('A {mood}, {tempo} {genre} layered with {instrument} textures.'),
('A {genre} anthem inspired by {era}, {energy} mood, and {twist}.'),
('An expressive {mood} {genre} piece with {instrument} and {tempo} pacing.'),
('A {mood} {genre} song performed {setting}, with {instrument} leading.'),
('Write a {tempo}, {mood} {genre} tune with {twist}.'),
('An {energy} {genre} track with {instrument}, blending {era} vibes.'),
('A {genre} that is {mood} and {tempo}, with {instrument} solos.'),
('Imagine {setting}: a {genre} performance with {twist} and {energy} mood.'),
('A {mood} {genre} infused with {era} sounds, {instrument}, and {tempo} beats.'),
('A {genre} number that feels {mood} and {energy}, with {instrument}.'),
('An {era}-inspired {genre} featuring {twist} and {instrument}.'),
('A {mood}, {tempo} {genre} played {setting} with {instrument}.'),
('Craft {genre} that blends {twist}, {mood}, and {instrument}.'),
('A {genre} creation influenced by {era}, {mood}, and {tempo}.'),
('An {energy} {genre} with {instrument}, layered with {twist}.'),
('Compose {mood} {genre} music {setting}, featuring {instrument}.'),
('A {tempo} {genre} that captures {mood}, with {era} inspiration.'),
('A {mood} {genre} groove enhanced with {instrument} and {twist}.'),
('A {genre} track, {energy} and {tempo}, played {setting}.'),
('Write {mood} {genre} with {instrument}, {era} tone, and {twist}.'),
('A {tempo}, {energy} {genre} anthem with {mood} vibes.'),
('A {mood} {genre} layered with {instrument}, performed {setting}.'),
('An {era} {genre} styled piece with {twist} and {mood} mood.'),
('A {genre} song featuring {instrument}, {mood} feel, and {tempo} beat.'),
('A {mood}, {tempo} {genre} with {twist}, inspired by {era}.'),
('A {genre} number played {setting}, with {instrument} and {energy}.'),
('Create {mood} {genre} in {era} style with {instrument} focus.'),
('A {tempo}, {mood} {genre} featuring {instrument} and {twist}.'),
('A {genre} jam, {energy} and {era}-infused, with {mood} tone.'),
('Compose a {mood} {genre} {tempo}, enhanced by {instrument}.'),
('An {energy} {genre} piece {setting}, with {twist} and {instrument}.');