// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbvsckoacdgpgiiqrhqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidnNja29hY2RncGdpaXFyaHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDg1ODEsImV4cCI6MjA3NDU4NDU4MX0.5RwQsg-GySXj3Gs63gCGBZwax2ujqd6G1nLaUcLejXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});